name: .NET Core

on: [push]

jobs:
  build:
    strategy:
        matrix:
            os: [ubuntu-latest, ubuntu-16.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Getting context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Getting code
      uses: actions/checkout@v1
      
    - name: Getting Nuget cache
      if: runner.os == 'Windows'
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - name: Run tests
      run: dotnet test --configuration Release
      
    - name: Try Publish(if the version has changed)
      if: runner.os == 'Windows'
      run: dotnet nuget push SimpleSocketIoClient\bin\Release\SimpleSocketIoClient.*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json; exit 0
